cp3:
  log:
    enabled: false
  webmvc:
    enabled: false
  database:
    tenantDatabasePrefix: cp3_extend
  ignore:
    token:
      - /ds/**
      - /**/noToken/**

spring:
  autoconfigure:
    exclude: io.seata.integration.http.HttpAutoConfiguration
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: oauth
          uri: lb://cp3-oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: tenant
          uri: lb://cp3-tenant-server
          predicates:
            - Path=/tenant/**
          filters:
            - StripPrefix=1
        - id: file
          uri: lb://cp3-file-server
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: authority
          uri: lb://cp3-authority-server
          predicates:
            - Path=/authority/**
          filters:
            - StripPrefix=1
        - id: msg
          uri: lb://cp3-msgs-server
          predicates:
            - Path=/msg/**
          filters:
            - StripPrefix=1
        - id: activiti
          uri: lb://cp3-activiti-server
          predicates:
            - Path=/activiti/**
          filters:
            - StripPrefix=1
        - id: demo
          uri: lb://cp3-demo-server
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: example
          uri: lb://cp3-example-server
          predicates:
            - Path=/example/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'


server:
  port: 8760
  servlet:
    context-path: /api
